# -*- coding: utf-8 -*-
"""comtours.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17YZj2sRFM0GvWxot-X8GsCQwHuCWmu_b
"""

import cv2 as cv
import numpy as np
from matplotlib import pyplot as plt

img = cv.imread('/content/Birds_culture-1-copy.jpeg')

blank = np.zeros(img.shape,dtype='uint8')
plt.imshow(blank)

gray = cv.cvtColor(img , cv.COLOR_BGR2GRAY)
  plt.imshow(gray)

blur = cv.GaussianBlur(gray,(5,5),cv.BORDER_DEFAULT)
plt.imshow(blur)

canny = cv.Canny(blur,125,125)
plt.imshow(canny)

ret, thresh = cv.threshold(gray, 125, 125, cv.THRESH_BINARY)
plt.imshow(thresh)

contours, hierarchies = cv.findContours(canny, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)
print(f'{len(contours)}contour(s)found!')

abc=cv.drawContours(blank, contours, -1, (0,0,255), 1)
plt.imshow(abc)